import Head from "next/head";

export default function AppHead({ title, favicon }) {
  return (
    <Head>
      <title>David Enomah</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/assets/favicon.ico" />
    </Head>
  );
}
